### ISSUE TITLE
Time tracker

### ISSUE THREAD

**Issue by amit05c** [Devashishsaurabh/fixed-thread-889#19]
- [x] create the stopwatch

- [x] create start and stop functionality

- [x] map the div in this page

- [x] store the date in the backend

- [x] responsive
